language: scala
scala:
  - 2.11.12

jdk:
  oraclejdk8

stages:
  - name: test

    # - name: release
    #    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    - stage: compile
      script: sbt compile
    - stage: test
      script: sbt coverage test
    - stage: report
      script: sbt coveralls

before_install:
  - git fetch --tags

after_success:
  - sbt coveralls
