language: scala
scala:
  - 2.12.15

dist: bionic

jdk:
  - oraclejdk11
  - openjdk11

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - env: TEST="test coverage"
      script: sbt compile coverage test coverageReport coverageAggregate coveralls
    - stage: release
      script: sbt ci-release

before_install:
  - git fetch --tags
