language: scala
scala:
  - 2.11.12

jdk:
  oraclejdk8

stages:
  - name: test

    # - name: release
    #    if: (branch = master AND type = push) OR (tag IS present)

jobs:
  include:
    - env: TEST="compile"
      script: sbt compile

before_install:
  - git fetch --tags

