addSbtPlugin("com.github.sbt"    % "sbt-ci-release" % "1.5.12")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"  % "2.0.8")
addSbtPlugin("org.scoverage"     % "sbt-coveralls"  % "1.3.9")
addSbtPlugin("com.julianpeeters" % "sbt-avrohugger" % "2.5.1")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"  % "0.11.0")
