addSbtPlugin("com.github.sbt"    % "sbt-ci-release" % "1.5.12")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"  % "2.2.0")
addSbtPlugin("org.scoverage"     % "sbt-coveralls"  % "1.3.13")
addSbtPlugin("com.julianpeeters" % "sbt-avrohugger" % "2.8.3")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"  % "0.11.0")
