addSbtPlugin("com.github.sbt"    % "sbt-ci-release" % "1.5.10")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"  % "1.9.2")
addSbtPlugin("org.scoverage"     % "sbt-coveralls"  % "1.3.1")
addSbtPlugin("com.julianpeeters" % "sbt-avrohugger" % "2.0.0")
addSbtPlugin("com.eed3si9n"      % "sbt-buildinfo"  % "0.11.0")
